# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AppStoreSearch' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire'
  pod 'Kingfisher'
  pod 'Cosmos', '~> 23.0'

  # Pods for SearchingAppStore

  target 'AppStoreSearchTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Alamofire'
    pod 'Kingfisher'
    pod 'Cosmos', '~> 23.0'
  end

  target 'AppStoreSearchUITests' do
    # Pods for testing
   pod 'Alamofire'
   pod 'Kingfisher'
   pod 'Cosmos', '~> 23.0'
  end

end
